name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  code-sniffer:
    name: PHP code sniffer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.1
          coverage: none
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction --no-ansi
      - name: Code sniffer
        run: composer phpcs

  mess-detector:
    name: PHP mess detector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.1
          coverage: none
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction --no-ansi
      - name: mess detector
        run: composer phpmd

  php-stan:
    name: PHP stan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.1
          coverage: none
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction --no-ansi
      - name: php stan
        run: composer phpstan

  tests:
    name: PHP ${{ matrix.php-versions }} Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.1', '7.2', '7.3']
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
    - name: Validate composer.json and composer.lock
      run: composer validate
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-interaction --no-ansi
    - name: Run test suite
      run: composer test
